# ----------- CONFIGURABLE START -----------
title:            Miracle Sean| Miracle Sean
description:      欢迎来到 Miracle Sean「思恩奇迹」天命玄鸟 闳识怀孤
url:              https://miracle-sean.github.io # 域名
site_name:        Miracle Sean
signoff:          Miracle Sean # Your name
google_analytics: UA-149746503-1
share:            true 
# 分页
paginate:         15  
paginate_path:    ":num"
plugins:          [jekyll-paginate]
links:
  - name:         首页
    url:          /
    external:     false
  - name:         书籍
    url:          /book
    external:     false
  - name:         旅游
    url:          /road
    external:     false
  - name:         归档
    url:          /archives
    external:     false
  # - name:         标签
  #   url:          /tags
  #   external:     false
  - name:         关于
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
